places=['australia','france','america','italy','russia']
print(places)
print(sorted(places))#临时排序
print(places)
print(sorted(places,reverse=True))#临时排反序
print(places)
places.reverse()#逆序
print(places)
places.reverse()#再逆一次
print(places)
places.sort()#不可逆排序
print(places)
places.sort(reverse=True)#不可逆排反序
print(places)
